[Date]
date.timezone = Asia/Ho_Chi_Minh

[PHP]
post_max_size = 100M
upload_max_filesize = 100M
variables_order = EGPCS
memory_limit = 512M
max_execution_time = 300
max_input_vars = 3000

; Error reporting
display_errors = Off
display_startup_errors = Off
log_errors = On
error_log = /var/log/php_errors.log

; Session
session.gc_probability = 0
session.gc_divisor = 1000

; OPcache
opcache.enable=1
opcache.revalidate_freq=0
opcache.validate_timestamps=1
opcache.max_accelerated_files=10000
opcache.memory_consumption=192
opcache.max_wasted_percentage=10
opcache.interned_strings_buffer=16
opcache.fast_shutdown=1